"""create subjects and documents tables

Revision ID: 9d22d3ffc4d8
Revises: 
Create Date: 2026-08-19 23:22:37.366365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d22d3ffc4d8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('subject_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('subject_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('documents',
    sa.Column('document_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('subject_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('chapter', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='UPLOADED', nullable=False),
    sa.Column('failed_stage', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.CheckConstraint("failed_stage IS NULL OR failed_stage IN ('EXTRACT', 'TRANSFORM', 'CHUNK', 'EMBEDDING', 'INDEX')", name='chk_documents_failed_stage'),
    sa.CheckConstraint("file_type IN ('pdf', 'txt', 'docx')", name='chk_documents_file_type'),
    sa.CheckConstraint("status IN ('UPLOADED', 'PROCESSING', 'INDEXED', 'FAILED', 'DELETED')", name='chk_documents_status'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_index(op.f('ix_documents_subject_id'), 'documents', ['subject_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_subject_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_table('subjects')
    # ### end Alembic commands ###
